### ISSUE TITLE
Add a licence and README

### ISSUE THREAD

**Issue by neanias** [compsoc-edinburgh/bi-drive-link#8]
Licensing software is always good and a README might be helpful for the ol' bus factor that you're pretty heavily involved with, @qaisjp...

**Comment by neanias** [comment]
I would say an MIT licence would probably be good.

**Comment by neanias** [comment]
([See community checklist](https://github.com/compsoc-edinburgh/bi-drive-link/community))

**Comment by qaisjp** [comment]
License added in 7e9c6c924cf7a8e4ffa8b21d2c3c41d549c0d69c
